# fly.toml app configuration file generated for getogether on 2023-05-09T07:19:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "getogether"
primary_region = "lax"

[env]
  PORT = "8081"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true